# Generated by Django 3.2.7 on 2021-09-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.IntegerField()),
                ('marca', models.CharField(max_length=150)),
            ],
        ),
    ]
