# Generated by Django 3.2.7 on 2021-09-26 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='fone',
            new_name='razao_social',
        ),
        migrations.AddField(
            model_name='company',
            name='telefone',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
